apiVersion: apps/v1
kind: Deployment
metadata:
  name: sheepit-sample-greeter
  labels:
    app: sheepit-sample-greeter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sheepit-sample-greeter
  template:
    metadata:
      labels:
        app: sheepit-sample-greeter
    spec:
      containers:
        - name: sheepit-sample-greeter
          image: repo.treescale.com/ryszalke/sheepit-sample-greeter:0.0.2
          ports:
            - containerPort: 8080
          env:
            - name: GREETER_NAME
              value: "{{GREETER_NAME}}"
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: sheepit-sample-greeter
  labels:
    app: sheepit-sample-greeter
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      nodePort: {{GREETER_PORT}}
  selector:
    app: sheepit-sample-greeter